@DiveCalculator_HostAddress = http://localhost:5069

GET {{DiveCalculator_HostAddress}}/weatherforecast/
Accept: application/json

GET {{DiveCalculator_HostAddress}}/divecalculator/
Accept: application/json

###
